name: CI/CD Pipeline for FastAPI

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Use the Python version your app requires

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests with pytest
      run: |
        pytest




  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t fastapi-app .

      # Step 6: Save Docker image as a tarball
      - name: Save Docker image
        run: |
          docker save -o fastapi-app.tar fastapi-app

      # Step 7: Copy Docker image to EC2 instance
      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "fastapi-app.tar"
          target: "/home/ubuntu/fastapi-app.tar"

      # Step 8: SSH into EC2 and deploy the app
      - name: Deploy app on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            docker load -i fastapi-app.tar
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d --name fastapi-app -p 8000:8000 fastapi-app